import type { Startup } from './types';

export const seedStartups: Startup[] = [
  {
    id: '1',
    company: 'Devtron',
    url: 'https://devtron.ai',
    description: 'Open-source Kubernetes dashboard and software delivery workflow platform.',
    sector: 'DevOps',
    investor: 'Alpha Wave, Lerer Hippeau',
    fundingStage: 'Seed',
    amount: '$12.0M',
    teamSize: 45,
    hiring: true,
    relevance: 'High',
    founderLinkedin: 'https://www.linkedin.com/in/prashantghildiyal/',
    outreachStatus: 'Not Started',
    lastContactDate: '2026-06-15',
    notes: 'Prashant is very active. Platform built on Kubernetes, great fit for our MLOps candidates.'
  },
  {
    id: '2',
    company: 'Keploy',
    url: 'https://keploy.io',
    description: 'API testing platform that generates test cases and data mocks from production traffic.',
    sector: 'DevOps / Testing',
    investor: 'Boldcap, Together Fund',
    fundingStage: 'Seed',
    amount: '$3.2M',
    teamSize: 18,
    hiring: true,
    relevance: 'High',
    founderLinkedin: 'https://www.linkedin.com/in/neharika-keploy/',
    outreachStatus: 'Messaged',
    lastContactDate: '2026-06-20',
    notes: 'Sent personalized message on LinkedIn referencing their open-source GitHub repo.'
  },
  {
    id: '3',
    company: 'Doctor Droid',
    url: 'https://drdroid.io',
    description: 'Observability platform for tracking process anomalies and business flow metrics.',
    sector: 'DevOps / Monitoring',
    investor: '3one4 Capital, Sequoia India Spark',
    fundingStage: 'Pre-Seed',
    amount: '$1.5M',
    teamSize: 12,
    hiring: true,
    relevance: 'High',
    founderLinkedin: 'https://www.linkedin.com/in/siddharth-singgh/',
    outreachStatus: 'Replied',
    lastContactDate: '2026-06-25',
    notes: 'Siddharth replied saying they are actively looking for a Senior DevOps engineer with GCP experience.'
  },
  {
    id: '4',
    company: 'TrueFoundry',
    url: 'https://www.truefoundry.com',
    description: 'MLOps platform helping startups deploy, track, and monitor machine learning models.',
    sector: 'MLOps',
    investor: 'Sequoia India Surge, Eniac Ventures',
    fundingStage: 'Seed',
    amount: '$3.2M',
    teamSize: 25,
    hiring: true,
    relevance: 'High',
    founderLinkedin: 'https://www.linkedin.com/in/nikunj-bajaj/',
    outreachStatus: 'Interviewing',
    lastContactDate: '2026-06-27',
    notes: 'Candidate Rohit is in round 2 (technical round). Feedback on team culture is highly positive.'
  },
  {
    id: '5',
    company: 'Last9',
    url: 'https://last9.io',
    description: 'Site reliability engineering database and observability tools for microservices.',
    sector: 'DevOps / Observability',
    investor: 'Sequoia Capital India, Better Capital',
    fundingStage: 'Series A',
    amount: '$11.0M',
    teamSize: 52,
    hiring: false,
    relevance: 'Medium',
    founderLinkedin: 'https://www.linkedin.com/in/nishantmodak/',
    outreachStatus: 'Closed',
    lastContactDate: '2026-05-10',
    notes: 'No immediate hiring plans in India; remote team mostly based in US/Europe currently.'
  },
  {
    id: '6',
    company: 'Facets.cloud',
    url: 'https://www.facets.cloud',
    description: 'Infrastructure-from-code platform simplifying cloud deployment and architecture setup.',
    sector: 'DevOps / IaC',
    investor: '3one4 Capital',
    fundingStage: 'Seed',
    amount: '$4.0M',
    teamSize: 32,
    hiring: true,
    relevance: 'High',
    founderLinkedin: 'https://www.linkedin.com/in/praveen-facets/',
    outreachStatus: 'Messaged',
    lastContactDate: '2026-06-24',
    notes: 'Reached out to Praveen regarding their Terraform/Kubernetes automation goals.'
  },
  {
    id: '7',
    company: 'InfraCloud',
    url: 'https://infracloud.io',
    description: 'Cloud-native consulting firm specializing in Kubernetes, Prometheus, and serverless.',
    sector: 'DevOps / Cloud Native',
    investor: 'Bootstrapped',
    fundingStage: 'Bootstrapped',
    amount: 'N/A',
    teamSize: 110,
    hiring: true,
    relevance: 'Medium',
    founderLinkedin: 'https://www.linkedin.com/in/vishal-biyani/',
    outreachStatus: 'Not Started',
    lastContactDate: '2026-06-01',
    notes: 'Good fallback for junior/mid DevOps roles. Large talent pool of Kubernetes certified specialists.'
  }
];
